# Generated by Django 6.0.2 on 2026-04-17 00:01

import tenantManagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenantManagement", "0002_tenantcomplaint"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="password",
            field=models.CharField(default=tenantManagement.models.default_tenant_password, max_length=128),
        ),
        migrations.AddField(
            model_name="tenant",
            name="password_updated",
            field=models.BooleanField(default=False),
        ),
    ]
