# Generated by Django 5.1.4 on 2026-04-24 16:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenantManagement', '0003_tenant_password_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='verification_token',
        ),
        migrations.AddField(
            model_name='tenant',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='room_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to='tenantManagement.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'expires_at'], name='tenantManag_tenant__d09356_idx')],
            },
        ),
    ]
