from django.urls import path
from .views import (
    create_tenant,
    resend_tenant_verification,
    tenant_verification_details,
    tenant_verification_rent_details,
    tenant_verification_rent_order,
    tenant_verification_rent_verify,
    submit_tenant_verification,
    tenant_rent_details,
    tenant_rent_order,
    tenant_rent_verify,
    tenant_profile,
    tenant_login,
    tenant_refresh_access_token,
    tenant_logout,
    tenant_room_details,
    tenant_rules,
    tenant_menu,
    tenant_complaints,
    delete_tenant,
    pending_verifications,
    upcoming_fees,
    tenants_list,
    complaints_list,
    verify_tenant_token,
    tenant_verification_token_details,
)

urlpatterns=[
    path("add-tenant/", create_tenant),
    path("tenant/register/", create_tenant),
    path("tenant/verify/", verify_tenant_token),
    path("tenant/verify/details/", tenant_verification_token_details),
    path("tenant/verify/rent/", tenant_verification_rent_details),
    path("tenant/verify/rent/order/", tenant_verification_rent_order),
    path("tenant/verify/rent/verify/", tenant_verification_rent_verify),
    path("tenant/verify/<uuid:token>/", verify_tenant_token),
    path("tenant/verify/resend/", resend_tenant_verification),
    path("tenant/details/<str:phone>/", tenant_verification_details),
    path("tenant/verify/submit/", submit_tenant_verification),
    path("tenant/<str:phone>/rent/", tenant_rent_details),
    path("tenant/<str:phone>/rent/order/", tenant_rent_order),
    path("tenant/<str:phone>/rent/verify/", tenant_rent_verify),
    path("tenant/<str:phone>/profile/", tenant_profile),
    path("tenant/login/", tenant_login),
    path("tenant/token/refresh/", tenant_refresh_access_token),
    path("tenant/logout/", tenant_logout),
    path("tenants/<int:tenant_id>/", delete_tenant),
    path("tenant/<str:phone>/room/", tenant_room_details),
    path("tenant/<str:phone>/menu/", tenant_menu),
    path("tenant/<str:phone>/complaints/", tenant_complaints),
    path("pending-verifications/", pending_verifications),
    path("upcoming-fees/", upcoming_fees),
    path("tenants/", tenants_list),
    path("complaints/", complaints_list),
   
]
